Added debug function for bash scripts

diff --git a/files/bash_functions b/files/bash_functions
--- a/files/bash_functions
+++ b/files/bash_functions
@@ -1,5 +1,34 @@
 # Collection of useful functions, should be loaded when sourcing .bashrc
 
+# A bash debug command:
+debug () {
+  # Runs the given bash script with extra diagnostics
+  # (print line numbers of each command and some other goodies)
+  LOGFILE=debug.txt
+
+  DEBUG='\e[2m[DEBUG]\e[22m'
+
+  if [[ $# -eq 0 ]] ; then
+    echo "Usage: debug script.sh [args]"
+    exit 1
+  fi
+  # Check if first argument is a bash script
+  echo -en "$DEBUG Checking if '$1' is a valid bash script..."
+  if grep '#!/bin/bash' "$1" > /dev/null; then
+    echo -e "\e[32m[ok]\e[0m"
+  else
+    echo -e "\e[31m[Fail]\e[0m"
+    echo "'$1' does not contain '#!/bin/bash"
+    exit 1
+  fi
+  
+  # Set format of debug prompt:
+  export PS4='\e[2m+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }\e[22m'
+  bash -x "$1" ${@:2} 2>&1 |tee "$LOGFILE" |less -r
+  echo -e "$DEBUG '$1' Finished with exit code: $?"
+  echo -e "$DEBUG log saved to '$LOGFILE', use 'less -r $LOGFILE' to review"
+}
+
 # Safe wrapper for colordiff:
 colordiff_safe () {
   # Check if colordiff is installed:
